### ISSUE TITLE
[ChatChart] [Feature Request] Disable ChatChart per channel without revoking user and/or bot access

### ISSUE THREAD

**Issue by rosegayming** [aikaterna/aikaterna-cogs#172]
An option to disable ChatChart per channel without revoking bot access would be nice as using permissions with any of the following settings does not work.
```yml
# Server permissions acl file
# Does not work
COMMAND:
 chatchart \#channel-name:
    role-id: false
  ``` 
```yml 
# Server permissions acl file
# Does not work
COMMAND:
 chatchart <#channel-id>:
    role-id: false
```
```yml
# Server permissions acl file
# Does not work
COMMAND:
 chatchart channel-id:
    role-id: false
  ```
